services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  fake-SMTP:
    image: reachfive/fake-smtp-server
    restart: always
    ports:
      - 1025:1025
      - 1080:1080
