export const Colors = {
  reset: "\x1b[0m",
  red: "\x1b[31m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  blue: "\x1b[34m",
  magenta: "\x1b[35m",
  cyan: "\x1b[36m",
  orange: "\x1b[130m",
  brightRed: "\x1b[91m",
  brightGreen: "\x1b[92m",
  brightYellow: "\x1b[93m",
  brightBlue: "\x1b[94m",
  brightMagenta: "\x1b[95m",
  brightCyan: "\x1b[96m",
};

export const DataColors = {
  0: Colors.red,
  1: Colors.green,
  2: Colors.yellow,
  3: Colors.blue,
  4: Colors.magenta,
  5: Colors.cyan,
  6: Colors.orange,
  7: Colors.brightRed,
  8: Colors.brightGreen,
  9: Colors.brightYellow,
  10: Colors.brightBlue,
  11: Colors.brightMagenta,
  12: Colors.brightCyan,
  100: Colors.reset,
};
