export const Colors = {
  red: "filter-red",
  green: "filter-green",
  yellow: "filter-yellow",
  lightblue: "filter-lightblue",
  pink: "filter-pink",
  purple: "filter-purple",
  olive: "filter-olive",
  orange: "#D35400",
  brightRed: "981212",
  brightGreen: "#00FF00",
  brightYellow: "FFD800",
  lightGreen: "#2ECC71 ",
  brightpink: "FF009B",
};

export const DataColors = {
  0: Colors.red,
  1: Colors.green,
  2: Colors.yellow,
  3: Colors.lightblue,
  4: Colors.pink,
  5: Colors.purple,
  6: Colors.olive,
  7: Colors.brightRed,
  8: Colors.brightGreen,
  9: Colors.brightYellow,
  10: Colors.lightGreen,
  11: Colors.brightpink,
  12: Colors.orange,
};
